---
- name: Instalar Zabbix Agent
  hosts: zabbix
  become: true

  tasks:
    - name: Adicionar repositório Zabbix (se necessário)
      apt_repository:
        repo: 'deb http://repo.zabbix.com/zabbix/5.4/ubuntu/ focal main'
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Instalar pacotes necessários
      apt:
        name: ['zabbix-agent']
        state: present
      when: ansible_os_family == 'Debian'

    - name: Habilitar e iniciar o serviço Zabbix Agent
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    # Adicionar tarefas para outros sistemas operacionais, se necessário

    - name: Adicionar regra de firewall (se necessário)
      ufw:
        rule: allow
        port: 10050
        proto: tcp
      become: true
      when: ansible_os_family == 'Debian'  # Ou outro sistema operacional suportado

    - name: Copiar arquivo de configuração do Zabbix Agent
      template:
        src: zabbix_agent.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - restart zabbix-agent
      when: ansible_os_family == 'Debian'  # Ou outro sistema operacional suportado

  handlers:
    - name: restart zabbix-agent
      systemd:
        name: zabbix-agent
        state: restarted
